version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webn5
      MYSQL_USER: datlt
      MYSQL_PASSWORD: dat
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
